//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnWinform_Demo02
{
    using System;
    using System.Collections.Generic;
    
    public partial class HoaDonCungCap
    {
        public HoaDonCungCap()
        {
            this.ChiTietHoaDonCungCaps = new HashSet<ChiTietHoaDonCungCap>();
        }
    
        public string MaHD { get; set; }
        public Nullable<System.DateTime> NgayLap { get; set; }
        public string MaNCC { get; set; }
    
        public virtual ICollection<ChiTietHoaDonCungCap> ChiTietHoaDonCungCaps { get; set; }
        public virtual NhaCungCap NhaCungCap { get; set; }
    }
}
