//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnWinform_Demo02
{
    using System;
    using System.Collections.Generic;
    
    public partial class LichLamViec
    {
        public LichLamViec()
        {
            this.NhanViens = new HashSet<NhanVien>();
        }
    
        public string MaLLV { get; set; }
        public string TenLLV { get; set; }
        public Nullable<System.TimeSpan> TgBatDau { get; set; }
        public Nullable<System.TimeSpan> TgKetThuc { get; set; }
    
        public virtual ICollection<NhanVien> NhanViens { get; set; }
    }
}
