//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnWinform_Demo02
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoaiNguyenLieu
    {
        public LoaiNguyenLieu()
        {
            this.NguyenLieux = new HashSet<NguyenLieu>();
        }
    
        public string MaLoaiNL { get; set; }
        public string TenLoaiNL { get; set; }
    
        public virtual ICollection<NguyenLieu> NguyenLieux { get; set; }
    }
}
