//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnWinform_Demo02
{
    using System;
    using System.Collections.Generic;
    
    public partial class NguyenLieu
    {
        public NguyenLieu()
        {
            this.ChiTietHoaDonCungCaps = new HashSet<ChiTietHoaDonCungCap>();
            this.ThucUongs = new HashSet<ThucUong>();
        }
    
        public string MaNL { get; set; }
        public string TenNL { get; set; }
        public string MaLoaiNL { get; set; }
    
        public virtual ICollection<ChiTietHoaDonCungCap> ChiTietHoaDonCungCaps { get; set; }
        public virtual LoaiNguyenLieu LoaiNguyenLieu { get; set; }
        public virtual ICollection<ThucUong> ThucUongs { get; set; }
    }
}
