//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnWinform_Demo02
{
    using System;
    using System.Collections.Generic;
    
    public partial class NhaCungCap
    {
        public NhaCungCap()
        {
            this.HoaDonCungCaps = new HashSet<HoaDonCungCap>();
        }
    
        public string MaNCC { get; set; }
        public string TenNCC { get; set; }
    
        public virtual ICollection<HoaDonCungCap> HoaDonCungCaps { get; set; }
    }
}
