//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnWinform_Demo02
{
    using System;
    using System.Collections.Generic;
    
    public partial class NhanVien
    {
        public NhanVien()
        {
            this.HoaDonThanhToans = new HashSet<HoaDonThanhToan>();
        }
    
        public string MaNV { get; set; }
        public string HoTenNV { get; set; }
        public Nullable<System.DateTime> NgSinh { get; set; }
        public string DiaChi { get; set; }
        public string Phai { get; set; }
        public string MaLLV { get; set; }
    
        public virtual ICollection<HoaDonThanhToan> HoaDonThanhToans { get; set; }
        public virtual LichLamViec LichLamViec { get; set; }
    }
}
